dockered owner
BUAA-BDA/OpenHuFu pull request #156
Opened 2023-08-02 07:39 UTC by Qwtdgh

process owner.sh in docker

2023-08-02 07:40 UTC, Qwtdgh commented
@SongY123

2023-08-04 09:38 UTC, SongY123 requested changes

2023-08-04 09:38 UTC, SongY123 commented on adapter/adapter-csv/pom.xml
> +          <dockerHost>http://127.0.0.1:2375</dockerHost>
Do not specify docker host here.

2023-08-04 09:38 UTC, SongY123 commented on owner/pom.xml
> +          <dockerHost>http://127.0.0.1:2375</dockerHost>
Do not specify docker host here.

2023-08-04 09:38 UTC, SongY123 commented on owner/src/main/docker/Dockerfile
Add a new folder named with 'docker-build' in project root path and move this Dockerfile to the folder.

2023-08-04 14:35 UTC, Qwtdgh commented on adapter/adapter-csv/pom.xml
> +          <dockerHost>http://127.0.0.1:2375</dockerHost>
resolve

2023-08-04 14:35 UTC, Qwtdgh commented on owner/src/main/docker/Dockerfile
resolve

2023-08-07 04:32 UTC, SongY123 approved these changes

2023-08-07 04:32 UTC, merged